/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FlowchartListRelationFilter } from "../../flowchart/base/FlowchartListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { NoteListRelationFilter } from "../../note/base/NoteListRelationFilter";
import { UmlDiagramListRelationFilter } from "../../umlDiagram/base/UmlDiagramListRelationFilter";
import { UnitWhereUniqueInput } from "../../unit/base/UnitWhereUniqueInput";

@InputType()
class TopicWhereInput {
  @ApiProperty({
    required: false,
    type: () => FlowchartListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FlowchartListRelationFilter)
  @IsOptional()
  @Field(() => FlowchartListRelationFilter, {
    nullable: true,
  })
  flowcharts?: FlowchartListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => NoteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NoteListRelationFilter)
  @IsOptional()
  @Field(() => NoteListRelationFilter, {
    nullable: true,
  })
  notes?: NoteListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UmlDiagramListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UmlDiagramListRelationFilter)
  @IsOptional()
  @Field(() => UmlDiagramListRelationFilter, {
    nullable: true,
  })
  umlDiagrams?: UmlDiagramListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UnitWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UnitWhereUniqueInput)
  @IsOptional()
  @Field(() => UnitWhereUniqueInput, {
    nullable: true,
  })
  unit?: UnitWhereUniqueInput;
}

export { TopicWhereInput as TopicWhereInput };
