/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Topic } from "./Topic";
import { TopicCountArgs } from "./TopicCountArgs";
import { TopicFindManyArgs } from "./TopicFindManyArgs";
import { TopicFindUniqueArgs } from "./TopicFindUniqueArgs";
import { CreateTopicArgs } from "./CreateTopicArgs";
import { UpdateTopicArgs } from "./UpdateTopicArgs";
import { DeleteTopicArgs } from "./DeleteTopicArgs";
import { FlowchartFindManyArgs } from "../../flowchart/base/FlowchartFindManyArgs";
import { Flowchart } from "../../flowchart/base/Flowchart";
import { NoteFindManyArgs } from "../../note/base/NoteFindManyArgs";
import { Note } from "../../note/base/Note";
import { UmlDiagramFindManyArgs } from "../../umlDiagram/base/UmlDiagramFindManyArgs";
import { UmlDiagram } from "../../umlDiagram/base/UmlDiagram";
import { Unit } from "../../unit/base/Unit";
import { TopicService } from "../topic.service";
@graphql.Resolver(() => Topic)
export class TopicResolverBase {
  constructor(protected readonly service: TopicService) {}

  async _topicsMeta(
    @graphql.Args() args: TopicCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Topic])
  async topics(@graphql.Args() args: TopicFindManyArgs): Promise<Topic[]> {
    return this.service.topics(args);
  }

  @graphql.Query(() => Topic, { nullable: true })
  async topic(
    @graphql.Args() args: TopicFindUniqueArgs
  ): Promise<Topic | null> {
    const result = await this.service.topic(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Topic)
  async createTopic(@graphql.Args() args: CreateTopicArgs): Promise<Topic> {
    return await this.service.createTopic({
      ...args,
      data: {
        ...args.data,

        unit: args.data.unit
          ? {
              connect: args.data.unit,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Topic)
  async updateTopic(
    @graphql.Args() args: UpdateTopicArgs
  ): Promise<Topic | null> {
    try {
      return await this.service.updateTopic({
        ...args,
        data: {
          ...args.data,

          unit: args.data.unit
            ? {
                connect: args.data.unit,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Topic)
  async deleteTopic(
    @graphql.Args() args: DeleteTopicArgs
  ): Promise<Topic | null> {
    try {
      return await this.service.deleteTopic(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Flowchart], { name: "flowcharts" })
  async findFlowcharts(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: FlowchartFindManyArgs
  ): Promise<Flowchart[]> {
    const results = await this.service.findFlowcharts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Note], { name: "notes" })
  async findNotes(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: NoteFindManyArgs
  ): Promise<Note[]> {
    const results = await this.service.findNotes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [UmlDiagram], { name: "umlDiagrams" })
  async findUmlDiagrams(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: UmlDiagramFindManyArgs
  ): Promise<UmlDiagram[]> {
    const results = await this.service.findUmlDiagrams(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Unit, {
    nullable: true,
    name: "unit",
  })
  async getUnit(@graphql.Parent() parent: Topic): Promise<Unit | null> {
    const result = await this.service.getUnit(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
