/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { Flowchart } from "../../flowchart/base/Flowchart";
import { Note } from "../../note/base/Note";
import { UmlDiagram } from "../../umlDiagram/base/UmlDiagram";
import { Unit } from "../../unit/base/Unit";

@ObjectType()
class Topic {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Flowchart],
  })
  @ValidateNested()
  @Type(() => Flowchart)
  @IsOptional()
  flowcharts?: Array<Flowchart>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Note],
  })
  @ValidateNested()
  @Type(() => Note)
  @IsOptional()
  notes?: Array<Note>;

  @ApiProperty({
    required: false,
    type: () => [UmlDiagram],
  })
  @ValidateNested()
  @Type(() => UmlDiagram)
  @IsOptional()
  umlDiagrams?: Array<UmlDiagram>;

  @ApiProperty({
    required: false,
    type: () => Unit,
  })
  @ValidateNested()
  @Type(() => Unit)
  @IsOptional()
  unit?: Unit | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Topic as Topic };
